_BASE_: "sparsercnn.crowdhuman.res50.500pro.50e.yaml"
MODEL:
  WEIGHTS: "/home/zhenganlin/june/CrowdHuman/dectron2-R-50.pkl"
  SparseRCNN:
    NUM_HEADS: 6
    IGNORE_THR: 0.7
    WATERSHED: 6
    CONFIDENCE_THR: 0.7
    RELATION_IOU_THR: 0.4
    ITER_NUM: 0
    LOW_CONFIDENCE_THR: 0.05
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00005
  STEPS: (37500,)
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "output"
