_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "/home/zhenganlin/june/CrowdHuman/R-50.pkl"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 500
    NUM_CLASSES: 1
DATASETS:
  TRAIN: ("CrowdHuman_train",)
  TEST:  ("CrowdHuman_val",)
SOLVER:
  STEPS: (7500,) # 15000 / 16 = 937.5
  MAX_ITER: 16875
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
  MAX_SIZE_TRAIN: 1500
  MIN_SIZE_TEST: 800
  MAX_SIZE_TRAIN: 1500
  CROP:
    ENABLED: False
  FORMAT: "RGB"
OUTPUT_DIR: "output/50e.6h.500pro"