_BASE_: "sparsercnn.crowdhuman.res50.500pro.50e.yaml"
MODEL:
  WEIGHTS: '/home/zhenganlin/june/CrowdHuman/dectron2-R-50.pkl'
  SparseRCNN:
    NUM_HEADS: 6
    IGNORE_THR: 0.7
    WATERSHED: 5
    RELATION_IOU_THR: 0.4
    CONFIDENCE_THR: 0.7
    ITER_NUM: 1
    LOW_CONFIDENCE_THR: 0.05
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00005 # base learning rate should be double if batch size of images is twice as much.
  STEPS: (37500,) # 15000 / 16 = 937.5
  MAX_ITER: 55000 #46875
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "output"
